Added CTemplar, #198
tycrek/degoogle pull request #200
Opened 2020-08-23 00:04 UTC by kabo

Resolves #198

2020-08-30 06:46 UTC, kabo commented
> Could you please remove all edits to README.md? Per [CONTRIBUTING.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md):
> 
> > As of May 25 2020, the `README.md` file is automatically generated. Please edit anything in `yaml/` or `md/`.

Hmmm... I didn't edit anything in README.md. The weird thing is when I try to push it says I need to pull because there are changes. So I run `git pull --rebase` as per usual, and then `git push`. I've no idea where those changes came from.

2020-09-28 22:50 UTC, tycrek requested changes
Sorry for the (very large) delay. It seems there are still changes in README.md on your branch. I would attempt to fix them myself but the GitHub web editor is being a PITA today.

2020-09-28 22:50 UTC, tycrek commented on README.md
> +![Updated](https://img.shields.io/static/v1?label=updated&message=August%2030th%202020&color=388E3C&style=flat-square)
Revert these changes

2020-09-28 22:50 UTC, tycrek commented on README.md
> +| [CTemplar](https://ctemplar.com/) |  | Privacy-focused email provider located in Iceland. |
This change as well

2020-10-13 09:49 UTC, kabo commented
The @actions-user didn't mess stuff up this time by the looks of it. Better now @tycrek ?

2020-10-19 17:48 UTC, tycrek commented
I think I finally know where that issue is coming from on the last line in the README. Testing something to confirm.

2020-10-19 17:53 UTC, tycrek commented
Didn't fix it. I'll merge this and hope nothing breaks.

2020-10-19 17:54 UTC, merged