DeltaChat is a Gmail app alternative
tycrek/degoogle pull request #261
Opened 2020-09-02 09:23 UTC by monperrus

2020-09-28 23:00 UTC, tycrek commented
I'm not sure I understand what this is. Is it just a standard mail client that looks like a messaging app? A lot of their "features" are just standard email features.

2020-09-29 05:15 UTC, monperrus commented
Yes it's a full-fledged email client, hence this PR to add it.

2020-09-29 18:23 UTC, tycrek commented on yaml/degoogle.yml
> +        Supports autocrypt
Text should be a bit more descriptive

2020-09-29 18:24 UTC, tycrek requested changes
Only thing before I merge is the `text` should be a bit more descriptive (I know others have bad descriptions, this is something that will be worked on)

2020-09-30 06:41 UTC, monperrus commented on yaml/degoogle.yml
> +        Supports autocrypt
done @tycrek

2020-09-30 06:45 UTC, tycrek approved these changes
Thanks @monperrus!

2020-09-30 06:46 UTC, merged